# Generated by Django 5.2.5 on 2026-06-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_announcement_image_url_remove_event_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='external_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Внешнее изображение'),
        ),
        migrations.AddField(
            model_name='news',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на оригинал'),
        ),
    ]
