# Generated by Django 6.0.2 on 2026-06-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hsm", "0009_leadership_bio_leadership_bio_en_leadership_bio_kg_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HSMInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Высшая медицинская школа", max_length=255
                    ),
                ),
                ("title_en", models.CharField(blank=True, max_length=255)),
                ("title_kg", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("description_kg", models.TextField(blank=True)),
                ("history", models.TextField(blank=True)),
                ("history_en", models.TextField(blank=True)),
                ("history_kg", models.TextField(blank=True)),
                ("main_directions", models.TextField(blank=True)),
                ("main_directions_en", models.TextField(blank=True)),
                ("main_directions_kg", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Информация ВШМ",
                "verbose_name_plural": "Информация ВШМ",
            },
        ),
    ]
